### ISSUE TITLE
Checkout with Merchant App: Error 99008 Request to payment service could not be completed

### ISSUE THREAD

**Issue by j-s-a-m** [conichiGMBH/conichi-android-sdk#1]
When completing a checkout in the Merchant App version 1.5.0, the following error occurs.

This happens with our test hotel in PROD, i.e. venue id 8, name "Das Hotel Portal".

Please double-check.

![20160926_conichimerchantappcrashaftercheckout](https://cloud.githubusercontent.com/assets/6809386/18833881/346546d4-83f3-11e6-8583-21e995bb853f.png)

**Comment by konstantin-kiriushyn** [comment]
I redirected this question to @Antondomashnev. He will check the merchant side
