### ISSUE TITLE
conichi backend is picky on date and time that is set on user's device

### ISSUE THREAD

**Issue by j-s-a-m** [conichiGMBH/conichi-android-sdk#10]
> SDK version
All versions.

> Environment : production

> Stacktrace
{"error":"Invalid Timestamp!","errors":[{"code":473,"message":"Invalid Timestamp!"}]}

> Steps to reproduce
Set the time or date on the device to something that differs from the current date/time.

> Expected behavior
Ignore the timestamp the user has configured on his device. If possible, use the backend server's time instead.

> Actual behavior
A time mismatch on the user's device can make Smarthotel/conichi stop working.

**Comment by konstantin-kiriushyn** [comment]
@j-s-a-m Issue is verified and a fix is planned to happen in the nearest future.

**Comment by konstantin-kiriushyn** [comment]
Server doesn't depend on the user's device time any more
