### ISSUE TITLE
Core library dissapeared from artifactory

### ISSUE THREAD

**Issue by CameliaTripon** [conichiGMBH/conichi-android-sdk#12]
> SDK version: 2.11.0 (or any other)

The "core" library is not available anymore on the artifactory: http://artifactory.conichi.com/artifactory/libs-release-local

I also tried to use the demo project but same issue. Please add the library as quick as possible because we cannot compile the app now

![screen shot 2018-09-17 at 14 25 19](https://user-images.githubusercontent.com/12637965/45620475-bbdc6500-ba85-11e8-811f-c90c90e7d1c6.png)

![screen shot 2018-09-17 at 14 25 54](https://user-images.githubusercontent.com/12637965/45620467-b5e68400-ba85-11e8-89aa-0a50ad379a20.png)

**Comment by CameliaTripon** [comment]
Now "core" is available again. Thanks

**Comment by Ch3D** [comment]
@CameliaTripon could you confirm that the build is fine now?

**Comment by CameliaTripon** [comment]
Actually, the .aar files are not in the folder. Now just the folder appeared, but no resources http://artifactory.conichi.com/artifactory/libs-release-local/com/conichi/sdk/core/2.11.0/
![screen shot 2018-09-17 at 15 16 00](https://user-images.githubusercontent.com/12637965/45622478-c8b08700-ba8c-11e8-9774-5b33c3cf0afc.png)

**Comment by Ch3D** [comment]
okay, I'm looking into it

**Comment by Ch3D** [comment]
@CameliaTripon could you try now? Let me know the result

**Comment by CameliaTripon** [comment]
Now it cannot find android-sdk:android-beacon-library:unspecified. I should mention that we are not referring the android-beacon-library in the gradle.
This is what "dependency" task shows for conichi core (highlighted)
![screen shot 2018-09-17 at 15 37 51](https://user-images.githubusercontent.com/12637965/45623381-cef43280-ba8f-11e8-81d9-8791e609043e.png)

**Comment by Ch3D** [comment]
okay, I know the reason, let me fix.
Btw, could you tell me your skype or any other id so we could speed-up communications?

**Comment by CameliaTripon** [comment]
Yes, I'm camytripon on Skype

**Comment by CameliaTripon** [comment]
Everything is ok now. Issue closed
