### ISSUE TITLE
PROD: Push messages are not recieved in multiple cases

### ISSUE THREAD

**Issue by rekire** [conichiGMBH/conichi-android-sdk#2]
Hi,

in our app are multiple push notifications not received in prod like the chat messages or checkin status changes. However checkout messages with payment details are transmitted.

In the sandbox everything works fine as expected. Please check this.

**Comment by rekire** [comment]
Any updates or progress here?

**Comment by konstantin-kiriushyn** [comment]
No, not yet,  I'll check it. Please add the SDK version on which you experienced the issue.

**Comment by rekire** [comment]
This fails on 2.5.9, we did not check 2.5.10 yet, however this looks like a backend issue.

**Comment by cheredon** [comment]
@rekire on sandbox there were no disabled push notifications. You got the notifications about the all processes. On production for hrs api-key some notifications were disabled and you didn't receive it at all. So after yesterday changes you will receive all notifications which were disabled as silent.

**Comment by konstantin-kiriushyn** [comment]
According to the @cheredon feedback issue was resolved and confirmed.
