### ISSUE TITLE
Payment notifications not sending payment_amount and payment_currency

### ISSUE THREAD

**Issue by CameliaTripon** [conichiGMBH/conichi-android-sdk#4]
For the payment notification we used the values from payment_amount and payment_currency, but for now we are not receiving those values anymore.

This is an example on what we are receiving now:
`{venue_id=2, venue_name=Das Hotel Portal (T&T und BMW), google.sent_time=1506414817906, action=completed_transaction, notification_id=3736, message_title=conichi, category=payment, google.message_id=0:1506414817917898%c4d68da2f9fd7ecd, message=Das Hotel Portal (T&T und BMW) - A payment of EUR 8.00 has been successfully made to Das Hotel Portal (T&T und BMW).}`

We need the payment_amount and payment_currency in order to build the payment notification that we are showing in the app.

**Comment by Ch3D** [comment]
@CameliaTripon thanks for your report, we will check it

**Comment by cheredon** [comment]
@CameliaTripon  Hi Camelia, we fixed the issue and deployed to production and sandbox, could you please try and let us know about results. Thanks

**Comment by CameliaTripon** [comment]
Yes, it is ok now. Thank you :)
