### ISSUE TITLE
Merchant App: Error 99009 Unable to process payment, contact support

### ISSUE THREAD

**Issue by Ch3D** [conichiGMBH/conichi-android-sdk#5]
_From @j-s-a-m on September 26, 2017 14:44_

I post this issue here because I faced it after a reservation on an Android device, but I think it's independent of the guest's mobile device platform.

In the Merchant App (on iOS) , after charging the customer's check-out items and confirming check-out, the following error occurs:

"(Error: 99009) Unable to process payment, contact support!"

See screenshot: https://photos.app.goo.gl/9iSzhuSctHiozSYE3

Maybe this is caused by the test credit card that has been used (Theo Test, 5355 ... 1153).

But maybe not. Please double-check.

_Copied from original issue: conichiGMBH/android-sdk#434_

**Comment by Ch3D** [comment]
@j-s-a-m could you specify SDK version?

**Comment by Ch3D** [comment]
_From @j-s-a-m on September 26, 2017 15:15_

The SDK version on the guest's Android phone is 2.10.2.
The Merchant App's version first was 1.8.0, then 1.9.1. The error remains the same.

**Comment by Ch3D** [comment]
@j-s-a-m okay, thanks. One more thing please - what's the `venue_id` and which environment do you use (production | sandbox)?

**Comment by Ch3D** [comment]
_From @j-s-a-m on September 27, 2017 8:34_

It's venue_id 8 on PROD, see
https://app.conichi.com/cmc/venues/8/

**Comment by cheredon** [comment]
@Ch3D @antonio-elena  Hi both, the aborted transactions have the amount less than 50 cents, but sumup supports only from 1 unit currency due to cost of processing.

**Comment by Ch3D** [comment]
@j-s-a-m please check the comment above

**Comment by j-s-a-m** [comment]
Good to know, and yes, this matches the scenario. Thanks.

However, there is still the following two issues:

1.) The hotelier/receptionist does not understand what is happening. He needs an explanation instead of a cryptic error message.

2.) More important: The check-out cannot be completed. 

Increasing the price of all check-out items to >= 1 unit seems like a workaround.

**Comment by cheredon** [comment]
@j-s-a-m Hi Johannes, we are going to update the messaging, thanks for support.
