### ISSUE TITLE
core-2.11.0-beta1.aar in artifactory is broken

### ISSUE THREAD

**Issue by j-s-a-m** [conichiGMBH/conichi-android-sdk#7]
> SDK version
2.11.0-beta1/core-2.11.0-beta1.aar

The file 

http://artifactory.conichi.com/artifactory/libs-release-local/com/conichi/sdk/core/2.11.0-beta1/core-2.11.0-beta1.aar

contains no classes.

The file properties as of today (04. Nov 2017) are
core-2.11.0-beta1.aar        11-Oct-2017 12:37  4.44 KB

You can see by the file size (4.44 KB) that something is odd. Unzip the aar to see that classes.jar is empty.

"2.11.0-beta1" is the version we are currently working with.

Please fix.

**Comment by Ch3D** [comment]
Do you know that there are `2,11.0-beta2`, `2,11.0-beta3` and `2,11.0-rc1` released.
Probably you should use the last one
